BuzzTalk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls',namespace='posts')),
    path('comment/',include('Comment.urls',namespace='Comment')),
    path('profile/',include('profiles.urls',namespace='profiles')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/',include('users.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

Comment/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import CommentView

app_name='Comment'

urlpatterns = [
    path('',CommentView,name='post-comment')
]

posts/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView,like_view,edit_view,delete_view,PostView
app_name='posts'

urlpatterns = [
    path('',HomeView,name='home'),
     path('edit/<int:pk>',edit_view,name='edit-post'),
     path('delete/',delete_view,name='delete-post'),
    path('like/',like_view,name='like-view'),
    path('post/',PostView,name='post-view')
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator


# Create your models here.
class UserPostModel(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField(max_length=100)
    image = models.ImageField(upload_to='posts',validators=[FileExtensionValidator(['png','jpg','jpeg'])],blank=True,null=True)
    likes = models.ManyToManyField(User,related_name = "likes",blank=True)
    profile = models.ForeignKey('profiles.Profile',on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

   
    def __str__(self):
        return self.text[:30]
    
    def count_likes(self):
        return self.likes.count()

    def count_comment(self):
        return self.comment_set.count()
    
    def all_comments(self):
        return self.comment_set.all()

    @property
    def get_image_url(self):
        try:
            url =self.image.url
        except:
            url=''
        return url
    
   


    class Meta:
        verbose_name = 'All Posts'
        verbose_name_plural = 'All Posts'
    

posts/forms.py
from django.forms import ModelForm
from .models import UserPostModel

class UserPostEditForm(ModelForm):
       
    class Meta:
        model = UserPostModel
        fields=('text','image')


class UserPostForm(ModelForm):
       
    class Meta:
        model = UserPostModel
        fields= ('user','text','image','profile',)

posts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import ListView
from .models import UserPostModel
from profiles.models import Profile
from django.http import JsonResponse
from .forms import UserPostEditForm,UserPostForm
from django.contrib.auth.models import User
from itertools import chain
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def HomeView(request):
    object_list= UserPostModel.objects.all().exclude()

    all_posts=[]
    combine_queryset=[]
    q = UserPostModel.objects.none()
    form=UserPostForm()
    # get profiles of everyone that the llogged in user is following
    all_profiles = Profile.objects.get(user=request.user).following.all() 
    all_profiles =list(all_profiles)
    # logged in user posts
    request_user_posts = UserPostModel.objects.filter(user=request.user)
    request_user_posts= list(request_user_posts)
    
    for i in all_profiles:
       combine_queryset+=q|UserPostModel.objects.filter(user=i.id)
    request_user_posts+= combine_queryset   
    all_posts.extend(request_user_posts)
    all_posts.reverse()
    
    #sort list
    for j in range(len(all_posts)):
        swapped=False
        i=0
        while i<len(all_posts)-1:
            if all_posts[i].created>all_posts[i+1].created:
                all_posts[i],all_posts[i+1]=all_posts[i+1],all_posts[i]
                swapped=True 
            i=i+1
        if swapped==False:
            break
    all_posts.reverse()
    return render(request,'posts/index.html',{'object_list':all_posts,'form':form})

@login_required
def PostView(request):
    form = UserPostForm()
    if request.method == 'POST':
            form = UserPostForm(request.POST or None,request.FILES or None)
            if form.is_valid():
                form.save()
                return redirect('posts:home')
    return render(request,'posts/post-content.html',{'form':form})


@login_required
def edit_view(request,pk):
    post = UserPostModel.objects.get(pk=pk)
    form = UserPostEditForm(instance=post)
    if request.method == 'POST':
        form = UserPostEditForm(request.POST or None,request.FILES or None,instance=post)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return redirect('/edit'+'/'+'{}'.format(pk))

    return render(request,'posts/edit-posts.html',{'form':form,'post':post})

@login_required
def delete_view(request):
    if request.method == 'POST':
        pk = request.POST.get('post_id')
        post = get_object_or_404(UserPostModel,pk=pk)
        post.delete()
        return redirect('/')

@login_required
def like_view(request):
    if request.method=='POST':
        pk = request.POST.get('post_id')
        post = get_object_or_404(UserPostModel,pk=pk)
        liked=False
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            return redirect('/')
        else:
            post.likes.add(request.user)
        return redirect('/')
    else:
        return redirect('/')

    


    

templates/posts/edit-posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Posts{% endblock title %}
{% block content %}


{% if request.user.is_authenticated %}


<section class="container">
    {% if post.user == request.user %}
    <form action="" method="POST" enctype="multipart/form-data" class="ui form" >
        {% csrf_token %}
        <div class="container the-form">
            <h1 class="text-center mb-3 mt-5">Edit Post</h1>
            {{form}}
           <div class="text-center">
            <button class="ui blue button">Update Changes</button>
           </div>
        </div>
        {% else %}
        <a class="ui header">Hey this is not your post stop trying nonsense</a>
      {% endif %}
        
    </form>
</section>
  
{% endif %}
{% endblock content %}

templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}


    <style>
        .post-img{
            
            max-height:300px;
            max-width:300px;
        }
    </style>
    <div class="ui container">
        <div class="ui grid">
            <div class="eight wide column">
                {% if object_list %}

                    {% for post in object_list%}
                <div class="ui fluid card">
                    <div class="content">
                        <div class="right floated meta">
                            <div class="ui grid">
                                {% if post.user == request.user %}
                                <div class="row">
                                    <form action="{% url 'posts:edit-post' post.pk %}" method="POST">
                                        {% csrf_token %}
                                        <button class="ui button bwhite-lg " type="submit">Update</button>
                                    </form>
                                   <form action="{% url 'posts:delete-post' %}" method="Post">
                                   {% csrf_token %}
                                       <input type="text" name="post_id" value="{{post.pk}}" hidden>
                                        <button class="ui button bwhite-lg" type="submit"  >Delete</button>
                                   </form>
    
                                </div>
                                {% endif %}
                            </div>
    
                        </div>
                        <img class="ui avatar image " src="{{post.profile.get_avatar_url}}">
                        {{post.user}}- Posted {{post.created|timesince}} ago  {% ifnotequal post.updated post.created %}(Updated){% endifnotequal %} 
                    </div>
                    <div class="ui fluid image">
                        <img class="ui medium rounded image" src="{{post.get_image_url}}" >
                    </div>
                    <div class="content">
                        <p>{{post.text}} {{p.all_following}} </p>
                    </div>
    
                    <div class="extra content ui grid two columns">
                       <form action="{% url 'posts:like-view' %}" method="POST">
                           {% csrf_token %}
                        <input type="hidden" name="post_id" value={{post.pk}}>
                        <button class="ui blue button ">{{post.count_likes}} Likes &nbsp;<i class="thumbs up icon"></i></button>
                       </form>
                        <button class="cmt_btn ui button mb-5">{{post.count_comment}} comment(s)</button>
                        <div class="ui container comment-box" style="display: none;">
                            {% if post.all_comments %}
                            {% for comment in post.all_comments %}
                            <div class="ui container mb-5">
                                <img class="ui avatar image" src="{{comment.post.profile.avatar.url}}">
                                <span>{{comment.author}}-{{comment.comment_post_date|timesince}}</span>
                                <div class='mt-5'>{{comment.comment}}</div>   
                            </div>
                            {% endfor %}
                            {% endif %}
                            
                            <hr>
                            <form action="{% url 'Comment:post-comment' %}" method="POST"class='ui fluid form'>
                                {% csrf_token %}
                                <input type="hidden" name="post_pk" value={{post.id}}>
                                <input type="text" name="comment" id="">
                                <button type="submit" name="submit_c_form" class="ui primary button mt-5 w-full">Send</button>
                            </form>
                        </div>
                        
                    </div>
                </div>
                {% endfor %}
                
                {% else %}
                    <h3>You have no post.Create one now</h3>
                {% endif %}
            </div>
            
            <div class="five wide column">
                <div class="ui segment">
                    
                    <form action= "{% url 'posts:post-view' %}" method="POST" class='ui form' enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form}} 
                        <button type='submit' name="" class="ui positive button w-full mt-5">Send</button>
                    </form>
                </div>
            </div>
        </div>
    
    </div>

       
</body>

</html>

<script>
    $(document).ready(function () {
        let display = false
        $(".cmt_btn").click(function () {
            if (display === false) {
                $(this).next(".comment-box").show("slow");
                display = true
            } else {
                $(this).next(".comment-box").hide("slow");
                display = false
            }
        });
    });
  

    const selector =  [...document.getElementById('id_user')]
    const username= "{{request.user}}"
    for (const i in selector){
      if (username == selector[i].innerText)
      selector[i].selected=true
      $('#id_user').hide()
      $('label[for="id_user"]').hide()
     
    }

    const user_profile = "{{request.user.profile}}";
    const user_profile_selector =  [...document.getElementById('id_profile')]
    for (const i in user_profile_selector){
      if (user_profile == user_profile_selector[i].innerText)
      user_profile_selector[i].selected=true
      $('#id_profile').hide()
      $('label[for="id_profile"]').hide()
     
    }
</script>

{% block scripts %}
<script src="{% static 'js/jquery.min.js'%}"></script>
{% endblock scripts %}

{% endblock content %}

templates/posts/post-content.html
 {% extends 'base.html' %}
 {% load static %}
{% block title %}Create Post{% endblock title %}
 {% block content %}
    <form class="ui form" enctype="multipart/form-data" action="{% url 'posts:post-view' %}" method="POST">
        {% csrf_token %}
        {{form}}
  <button class="ui primary button" type="submit" name="mobile_form" style="margin-top: 20px !important;margin-bottom:20px !important;">Submit</button>
</form>

<script>
   const selector =  [...document.getElementById('id_user')]
    const username= "{{request.user}}"
    for (const i in selector){
      if (username == selector[i].innerText)
      selector[i].selected=true
      $('#id_user').hide()
      $('label[for="id_user"]').hide()
     
    }

    const user_profile = "{{request.user.profile}}";
    const user_profile_selector =  [...document.getElementById('id_profile')]
    for (const i in user_profile_selector){
      if (user_profile == user_profile_selector[i].innerText)
      user_profile_selector[i].selected=true
      $('#id_profile').hide()
      $('label[for="id_profile"]').hide()
     
    }
</script>

 {% endblock content%}