BuzzTalk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls',namespace='posts')),
    path('comment/',include('Comment.urls',namespace='Comment')),
    path('profile/',include('profiles.urls',namespace='profiles')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/',include('users.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView,like_view,edit_view,delete_view,PostView
app_name='posts'

urlpatterns = [
    path('',HomeView,name='home'),
     path('edit/<int:pk>',edit_view,name='edit-post'),
     path('delete/',delete_view,name='delete-post'),
    path('like/',like_view,name='like-view'),
    path('post/',PostView,name='post-view')
]

profiles/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import ProfileView,EditProfileView,AllProfilesView,DetailProfilesView,follow_unfollow_view

app_name='profiles'

urlpatterns = [
    path('',ProfileView,name='profile-view'),
    path('edit-profile/',EditProfileView,name='edit-profile'),
    path('all-profiles/',AllProfilesView,name='all-profiles'),
    path('profile/<slug>',DetailProfilesView,name='view-another-profile'),
    path('follow/',follow_unfollow_view,name='follow-another-profile'),
]

users/urls.py
from django.contrib import auth
from django.contrib.auth.views import PasswordChangeView
from django.urls import path,include
from .views import RegisterView,ChangePassword,PasswordChanged,UserLogin


app_name='users'

urlpatterns = [
    path('register/',RegisterView.as_view(),name='register'),
    path('login/',UserLogin.as_view(),name='login'),
    path('change-password/',ChangePassword.as_view(),name='password-reset'),
    path('password-change-done/',PasswordChanged.as_view(),name='password_change_done'),
   
   
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <link rel="stylesheet" href="{% static '/css/semantic.min.css' %}">
    
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <title>BuzzTalk | {% block title %}{% endblock title %}</title>
</head>
<body>

     {% include 'navbar.html' %}
    
     <div class="ui container">
        {% block content %}
        {% endblock content %}
     </div>
   
    
    <script src="{% static 'js/semantic.min.js' %}"></script>
    
</body>
</html>

templates/navbar.html
{% load static %}
{% block mycss %}
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

{% endblock mycss %}
    <nav style="margin-bottom: 20px !important" >
        <header class="ui container " style="height:100% !important;">
        
            <div class="hamburger">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
              </div>
              <ul class="nav-links">
                <li><a href="{% url 'posts:home' %}">Home</a></li>
                <li><a href="{% url 'posts:post-view' %}">Post </a></li>
                <li><a href="{% url 'profiles:all-profiles' %}">All Users</a></li>
                <li class="" style="display: flex !important; align-items:center; ">
                    <div><img class="ui mini circular image" src="{{picture}}"></div>
                    <div style="margin-left:10px !important;">
                        <form action="{% url 'profiles:profile-view' %}" method="GET">
                            <button class="ui primary button" type="submit">Profile</button>
                        </form>
                        
                    </div>
                </li>
                 {% if not request.user.is_authenticated %}
                <li><a href="{% url 'users:register' %}">Register</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'users:password-reset' %}"> Change Password</a></li>
                {% endif %}
                
                
              </ul>
        </header>
    </nav>

{% block scripts %}
  <script src="{% static 'js/app.js' %}"></script>
{% endblock scripts %}