BuzzTalk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls',namespace='posts')),
    path('comment/',include('Comment.urls',namespace='Comment')),
    path('profile/',include('profiles.urls',namespace='profiles')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/',include('users.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView,like_view,edit_view,delete_view,PostView
app_name='posts'

urlpatterns = [
    path('',HomeView,name='home'),
     path('edit/<int:pk>',edit_view,name='edit-post'),
     path('delete/',delete_view,name='delete-post'),
    path('like/',like_view,name='like-view'),
    path('post/',PostView,name='post-view')
]

profiles/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import ProfileView,EditProfileView,AllProfilesView,DetailProfilesView,follow_unfollow_view

app_name='profiles'

urlpatterns = [
    path('',ProfileView,name='profile-view'),
    path('edit-profile/',EditProfileView,name='edit-profile'),
    path('all-profiles/',AllProfilesView,name='all-profiles'),
    path('profile/<slug>',DetailProfilesView,name='view-another-profile'),
    path('follow/',follow_unfollow_view,name='follow-another-profile'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from autoslug import AutoSlugField
from posts.models import UserPostModel
from Comment.models import Comment


# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio...", max_length=300,blank=True)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    followers = models.ManyToManyField(User, blank=True, related_name='followers')
    following = models.ManyToManyField(User, blank=True, related_name='following')
    slug = AutoSlugField(populate_from='user')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"slug": self.slug})
    
    def count_all_posts(self):
        return UserPostModel.objects.filter(user=self.user).count()

    def count_all_likes(self):
        count_likes=0
        all_post= UserPostModel.objects.filter(user=self.user).all()
        for post in all_post:
            if post.likes.filter(id=self.user.id).exists():
                count_likes+=1
        return count_likes
    
    def comment_count(self):
        all_comment = Comment.objects.filter(author=self.user).all().count()
        return all_comment
    
    def total_posts_likes_count(self):
        all_posts = UserPostModel.objects.filter(user=self.user)
        count=0
        for post in all_posts:
            count+=post.likes.count()
        return count
    
    def get_avatar_url(self):
        try:
            url =self.avatar.url
        except:
            url=''
        return url
    
    def count_followers(self):
        return self.followers.all().count()

    def count_following(self):
        return self.following.all().count()
    
    def all_following(self):
        return self.following.all()

    def all_followers(self):
        return self.followers.all()
    
   

    

profiles/forms.py
from django.forms import ModelForm 
from .models import Profile

class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = ('first_name','last_name','bio','email','country','avatar',)

profiles/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Profile
from .forms import ProfileForm
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def ProfileView(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'profiles/user-profile.html',{"profile":profile})

@login_required
def EditProfileView(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST or None,request.FILES or None,instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profiles:profile-view')
    return render(request,'profiles/edit-profile.html',{"form":form,'profile':profile})

@login_required
def AllProfilesView(request):
    all_profiles= Profile.objects.all().exclude(user=request.user)
    return render(request,'profiles/all-profiles.html',{"all_profiles":all_profiles})

@login_required
def DetailProfilesView(request,slug):
    #to view another user's profile
    profile =Profile.objects.get(slug=slug)
    return render(request,'profiles/another-user-profile.html',{'profile':profile})

@login_required
def follow_unfollow_view(request):
    if request.method == 'POST':
        person_to_follow_or_unfollow_profile_id = request.POST.get('profile_pk')
        person_to_unfollow_or_follow_profile = get_object_or_404(Profile,pk=person_to_follow_or_unfollow_profile_id)
        current_user_profile = get_object_or_404(Profile,pk=request.user.id)
        if not current_user_profile.following.filter(id=person_to_follow_or_unfollow_profile_id).exists():
            current_user_profile.following.add(person_to_unfollow_or_follow_profile.user)
            person_to_unfollow_or_follow_profile.followers.add(request.user)
            return redirect('profiles:all-profiles')
        elif current_user_profile.following.filter(id=person_to_follow_or_unfollow_profile_id).exists():
            current_user_profile.following.remove(person_to_unfollow_or_follow_profile.user)
            person_to_unfollow_or_follow_profile.followers.remove(request.user)
            return redirect('profiles:all-profiles')
        return redirect('profiles:all-profiles')
    else:
        return redirect('profiles:all-profiles')

templates/profiles/all-profiles.html
 {% extends 'base.html' %}
 {% load static %}

 {% block content %}
 {% block title %}All Profiles{% endblock title %}
{% if all_profiles %}
 {% for profile in all_profiles %}
 
      <div class="ui segment">
        <div class="ui grid">
          <div class="row">
            <div class="four wide column">
              <img class="ui small circular image" src="{{profile.get_avatar_url}}"> 
            </div>
            <div class="twelve wide column">
              <h3>{{profile.user}}</h3>
              <p>{{profile.bio|truncatechars:20}} </p>
              <p><span>Followers: {{profile.count_followers}}</span>
                <span>Following: {{profile.count_following}}</span></p>
                <div class="ui buttons">
                    <a href="{% url 'profiles:view-another-profile' profile.slug %}" ><button  class="ui primary button mb-5 w-big">View Profile</button></a>
                    <br>
                    <form action="{% url 'profiles:follow-another-profile' %}" method="POST">
                        {% csrf_token %}
                        <input type="text" name="profile_pk" value="{{profile.pk}}" hidden>    
                        {% if request.user in profile.all_followers %}       
                        <button type="submit" class="ui red  button mb-5 w-big" style="margin-left: 20px !important;">UnFollow</button>
                        {% else %}       
                        <button type="submit" class="ui positive basic button mb-5 w-big" style="margin-left: 20px !important;">Follow</button>
                        {% endif %}
                      </form>  
                        
                  </div>
              
            
                                
            </div>
          </div>
        </div>
      </div>
    
 {% endfor %}
 {% else %}
  <a class="header">Sorry there is no profile to yet</a>
 {% endif %}
 </div>
 {% endblock content%}

templates/profiles/another-user-profile.html
 {% extends 'base.html' %}
 {% load static %}
{% block title %}View Profile{% endblock title %}
 {% block content %}

 <div class="ui container segment padded">
     <div class="ui divided items">
         <div class="item">
             <div class="image">
                 <img src="{{profile.get_avatar_url}}">
             </div>
             <div class="content">


                 <div class="meta">
                     <div class="ui huge header">{{profile.first_name|title}} &nbsp; {{profile.last_name|title}}</div>
                     <div class="ui huge header">Username : {{profile.user|title}} </div>
                     <div class="ui header ">Country: {{profile.country}}</div>
                     <div class="ui header ">Bio: <span style="font-weight: normal !important;">{{profile.bio}}</span></div>
                     <div class="ui header ">Followers : <span style="font-weight: normal !important;">{{profile.count_followers}} &nbsp; people</span></div>
                     <div class="ui header ">Following: <span style="font-weight: normal !important;">{{profile.count_following}} &nbsp; people</span></div>
                     <div class="ui header ">No of Posts: <span
                             style="font-weight: normal !important;">{{profile.count_all_posts}}</span></div>
                     <div class="ui header ">No of Likes: <span
                             style="font-weight: normal !important;">{{profile.count_all_likes}}</span></div>
                     <div class="ui header ">No of Comments Made: <span
                             style="font-weight: normal !important;">{{profile.comment_count}}</span></div>
                     <div class="ui header ">No of Likes from all Posts: <span
                             style="font-weight: normal !important;">{{profile.total_posts_likes_count}}</span></div>
                 </div>
             </div>
         </div>
     </div>
 </div>
 </div>
 {% endblock content%}

templates/profiles/edit-profile.html
 {% extends 'base.html' %}
 {% load static %}
{% block title %}Edit Profile{% endblock title %}
 {% block content %}
  {% if request.user == profile.user %}

    <form class="ui form" enctype="multipart/form-data" action="{% url 'profiles:edit-profile' %}" method="POST">
        {% csrf_token %}
        {{form}}
  <button class="ui primary button" type="submit" style="margin-top: 20px !important;margin-bottom:20px !important;">Submit</button>
</form>
<!--
{% block scripts %}
<script>
    const selector =  [...document.getElementById('id_user')]
    const username= "{{request.user}}"
    for (const i in selector){
      if (username == selector[i].innerText)
      selector[i].selected=true
      $('#id_user').hide()
      $('label[for="id_user"]').hide()
     
    }
</script>
{% endblock scripts %}
-->
{% else %}
<h3>Sorry you cannot edit this profile</h3>
{% endif %}

 {% endblock content%}

templates/profiles/user-profile.html
 {% extends 'base.html' %}
 {% load static %}

 {% block content %}
 {% block title %}User Profile{% endblock title %}
{% if request.user == profile.user %}
 <div class="ui container segment padded">
     <div class="ui divided items">
         <div class="item">
             <div class="image">
                 <img src="{{profile.avatar.url}}">
             </div>
             <div class="content">
                 <div class="ui huge header">{{profile.first_name|title}} &nbsp; {{profile.last_name|title}} Profile</div>
                 <br><br>
                 <div class="meta">
                     <div class="ui header ">User: {{profile.user}}</div>
                     <div class="ui header ">Country: {{profile.country}}</div>
                     <div class="ui header ">Bio: <span style="font-weight: normal !important;">{{profile.bio}}</span></div>
                     <div class="ui header ">Followers : <span style="font-weight: normal !important;">{{profile.count_followers}} people</span></div>
                     <div class="ui header ">Following: <span style="font-weight: normal !important;">{{profile.count_following}} people</span></div>
                     <div class="ui header ">No of Posts: <span
                             style="font-weight: normal !important;">{{profile.count_all_posts}}</span></div>
                     <div class="ui header ">No of Likes: <span
                             style="font-weight: normal !important;">{{profile.count_all_likes}}</span></div>
                     <div class="ui header ">No of Comments Made: <span
                             style="font-weight: normal !important;">{{profile.comment_count}}</span></div>
                     <div class="ui header ">No of Likes from all Posts: <span
                             style="font-weight: normal !important;">{{profile.total_posts_likes_count}}</span></div>
                 </div>
                 <div class="extra">
                     <form action="{% url 'profiles:edit-profile' %}" method="GET">
                         <button class="ui green button">Edit Profile</button>
                     </form>
                 </div>
             </div>
         </div>
     </div>
 </div>
 </div>
{% else %}
<h3>Soory you cannot view this profile</h3>
 {% endif %}
 {% endblock content%}